# Generated by Django 2.2.1 on 2019-05-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64, unique=True)),
                ('country_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_price', models.IntegerField(max_length=10)),
                ('product_epic', models.CharField(max_length=64)),
                ('product_sku', models.CharField(max_length=200, unique=True)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_is_active', models.BooleanField(default=True)),
                ('product_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appefirst.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('lp', 'Landing'), ('pre', 'prelanding'), ('off', 'official'), ('oth', 'other')], max_length=30)),
                ('page_code', models.CharField(max_length=64)),
                ('page_url', models.CharField(max_length=300)),
                ('page_project_code', models.CharField(max_length=64)),
                ('page_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appefirst.Products')),
            ],
        ),
    ]
