# Generated by Django 2.2.1 on 2019-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appefirst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
