# Generated by Django 2.2.1 on 2019-06-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appefirst', '0002_auto_20190515_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(default=None, max_length=64)),
                ('domain_token', models.CharField(default=None, max_length=64)),
                ('domain_owner', models.CharField(choices=[('affbay', 'affbay'), ('zenia', 'zenia'), ('natalia', 'natalia'), ('user1', 'user1'), ('user2', 'user2'), ('user3', 'user3')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pages',
            name='page_is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_is_in_affbay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_is_smth1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_is_smth2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_notes1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_notes2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='product_is_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_is_smth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_notes',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_type',
            field=models.CharField(choices=[('lp', 'landing'), ('pre', 'prelanding'), ('off', 'official'), ('oth', 'other')], max_length=30),
        ),
    ]
