# Generated by Django 2.2.1 on 2019-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appefirst', '0003_auto_20190622_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
