# Generated by Django 2.2.6 on 2019-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appefirst', '0005_auto_20190622_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=20)),
                ('draw_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_name']},
        ),
    ]
